//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SPOT_NET_NATIVE_H_
#define _SPOT_NET_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_NetworkInterface
{
    static const int FIELD___interfaceIndex = 1;
    static const int FIELD___flags = 2;
    static const int FIELD___ipAddress = 3;
    static const int FIELD___gatewayAddress = 4;
    static const int FIELD___subnetMask = 5;
    static const int FIELD___dnsAddress1 = 6;
    static const int FIELD___dnsAddress2 = 7;
    static const int FIELD___networkInterfaceType = 8;
    static const int FIELD___macAddress = 9;

    TINYCLR_NATIVE_DECLARE(InitializeNetworkInterfaceSettings___VOID);
    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___VOID__I4);
    TINYCLR_NATIVE_DECLARE(GetNetworkInterfaceCount___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(GetNetworkInterface___STATIC__MicrosoftSPOTNetNetworkInformationNetworkInterface__U4);
    TINYCLR_NATIVE_DECLARE(IPAddressFromString___STATIC__U4__STRING);

    //--//

};

struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_Wireless80211
{
    static const int FIELD__Authentication = 10;
    static const int FIELD__Encryption = 11;
    static const int FIELD__Radio = 12;
    static const int FIELD__PassPhrase = 13;
    static const int FIELD__NetworkKey = 14;
    static const int FIELD__ReKeyInternal = 15;
    static const int FIELD__Ssid = 16;
    static const int FIELD__Id = 17;

    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___STATIC__VOID__MicrosoftSPOTNetNetworkInformationWireless80211__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SaveAllConfigurations___STATIC__VOID);

    //--//

};

struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_NetworkAvailabilityEventArgs
{
    static const int FIELD___isAvailable = 1;


    //--//

};

struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_NetworkChange
{
    static const int FIELD_STATIC__NetworkAddressChanged = 0;
    static const int FIELD_STATIC__NetworkAvailabilityChanged = 1;


    //--//

};

struct Library_spot_net_native_Microsoft_SPOT_Net_SocketNative
{
    TINYCLR_NATIVE_DECLARE(socket___STATIC__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(bind___STATIC__VOID__OBJECT__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(connect___STATIC__VOID__OBJECT__SZARRAY_U1__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(send___STATIC__I4__OBJECT__SZARRAY_U1__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(recv___STATIC__I4__OBJECT__SZARRAY_U1__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(close___STATIC__I4__OBJECT);
    TINYCLR_NATIVE_DECLARE(listen___STATIC__VOID__OBJECT__I4);
    TINYCLR_NATIVE_DECLARE(accept___STATIC__I4__OBJECT);
    TINYCLR_NATIVE_DECLARE(getaddrinfo___STATIC__VOID__STRING__BYREF_STRING__BYREF_SZARRAY_SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(shutdown___STATIC__VOID__OBJECT__I4__BYREF_I4);
    TINYCLR_NATIVE_DECLARE(sendto___STATIC__I4__OBJECT__SZARRAY_U1__I4__I4__I4__I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(recvfrom___STATIC__I4__OBJECT__SZARRAY_U1__I4__I4__I4__I4__BYREF_SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(getpeername___STATIC__VOID__OBJECT__BYREF_SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(getsockname___STATIC__VOID__OBJECT__BYREF_SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(getsockopt___STATIC__VOID__OBJECT__I4__I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(setsockopt___STATIC__VOID__OBJECT__I4__I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(poll___STATIC__BOOLEAN__OBJECT__I4__I4);
    TINYCLR_NATIVE_DECLARE(ioctl___STATIC__VOID__OBJECT__U4__BYREF_U4);

    //--//

};

struct Library_spot_net_native_Microsoft_SPOT_Net_NetworkInformation_NetworkChange__NetworkEvent
{
    static const int FIELD__EventType = 3;
    static const int FIELD__Flags = 4;
    static const int FIELD__Time = 5;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_Net;

#endif  //_SPOT_NET_NATIVE_H_
