//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "corlib_native.h"
#include "corlib_native_System_Math.h"

using namespace System;


HRESULT Library_corlib_native_System_Math::Round___STATIC__R8__R8( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        double param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double retVal = Math::Round( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_corlib_native_System_Math::Ceiling___STATIC__R8__R8( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        double param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double retVal = Math::Ceiling( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_corlib_native_System_Math::Floor___STATIC__R8__R8( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        double param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double retVal = Math::Floor( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_corlib_native_System_Math::Pow___STATIC__R8__R8__R8( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        double param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double param1;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 1, param1 ) );

        double retVal = Math::Pow( param0, param1, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}
