//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "corlib_native.h"
#include "corlib_native_System_TimeZone.h"

using namespace System;


HRESULT Library_corlib_native_System_TimeZone::GetTimeZoneOffset___STATIC__I8( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        INT64 retVal = TimeZone::GetTimeZoneOffset( hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT64( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}
