//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKStudio.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist.
        /// </summary>
        internal static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analise finished.
        /// </summary>
        internal static string AnaliseFinished {
            get {
                return ResourceManager.GetString("AnaliseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analise started.
        /// </summary>
        internal static string AnaliseStarted {
            get {
                return ResourceManager.GetString("AnaliseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        internal static string AutoHide {
            get {
                return ResourceManager.GetString("AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Progress.
        /// </summary>
        internal static string BuildProgress {
            get {
                return ResourceManager.GetString("BuildProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Library category.
        /// </summary>
        internal static string CloneLibraryCategory {
            get {
                return ResourceManager.GetString("CloneLibraryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        internal static string CloseAllButThis {
            get {
                return ResourceManager.GetString("CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component dependencies.
        /// </summary>
        internal static string ComponentDependencies {
            get {
                return ResourceManager.GetString("ComponentDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Error.
        /// </summary>
        internal static string ConsoleError {
            get {
                return ResourceManager.GetString("ConsoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Dependency.
        /// </summary>
        internal static string DeleteDependency {
            get {
                return ResourceManager.GetString("DeleteDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Feature Association.
        /// </summary>
        internal static string DeleteFeatureAssociation {
            get {
                return ResourceManager.GetString("DeleteFeatureAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Library.
        /// </summary>
        internal static string DeleteLibrary {
            get {
                return ResourceManager.GetString("DeleteLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Library Category.
        /// </summary>
        internal static string DeleteLibraryCategory {
            get {
                return ResourceManager.GetString("DeleteLibraryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document.
        /// </summary>
        internal static string DockAsTabbed {
            get {
                return ResourceManager.GetString("DockAsTabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string ENVIRONMENT {
            get {
                return ResourceManager.GetString("ENVIRONMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load options.
        /// </summary>
        internal static string ERROR_CANT_LOAD_OPTIONS {
            get {
                return ResourceManager.GetString("ERROR_CANT_LOAD_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save options.
        /// </summary>
        internal static string ERROR_CANT_SAVE_OPTIONS {
            get {
                return ResourceManager.GetString("ERROR_CANT_SAVE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature associations.
        /// </summary>
        internal static string FeatureAssociations {
            get {
                return ResourceManager.GetString("FeatureAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature dependencies.
        /// </summary>
        internal static string FeatureDependencies {
            get {
                return ResourceManager.GetString("FeatureDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureList.
        /// </summary>
        internal static string FeatureList {
            get {
                return ResourceManager.GetString("FeatureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all.
        /// </summary>
        internal static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string IDS_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("IDS_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: VISUAL C++ 10.0 is not installed on this machine.
        /// </summary>
        internal static string IDS_SET_ENV_ERROR_VS10_MISSING {
            get {
                return ResourceManager.GetString("IDS_SET_ENV_ERROR_VS10_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: VISUAL C++ 9.0 is not installed on this machine.
        /// </summary>
        internal static string IDS_SET_ENV_ERROR_VS9_MISSING {
            get {
                return ResourceManager.GetString("IDS_SET_ENV_ERROR_VS9_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPkDirectory.
        /// </summary>
        internal static string InvalidPkDirectory {
            get {
                return ResourceManager.GetString("InvalidPkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA.
        /// </summary>
        internal static string ISA {
            get {
                return ResourceManager.GetString("ISA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA Specific.
        /// </summary>
        internal static string ISASpecific {
            get {
                return ResourceManager.GetString("ISASpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library category.
        /// </summary>
        internal static string LibraryCategory {
            get {
                return ResourceManager.GetString("LibraryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Proj Cache.
        /// </summary>
        internal static string LibraryProjCache {
            get {
                return ResourceManager.GetString("LibraryProjCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingSolutions.
        /// </summary>
        internal static string LoadingSolutions {
            get {
                return ResourceManager.GetString("LoadingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Components.
        /// </summary>
        internal static string MatchingComponents {
            get {
                return ResourceManager.GetString("MatchingComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFProject.
        /// </summary>
        internal static string MFProject {
            get {
                return ResourceManager.GetString("MFProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Library category.
        /// </summary>
        internal static string NewLibraryCategory {
            get {
                return ResourceManager.GetString("NewLibraryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string OF {
            get {
                return ResourceManager.GetString("OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        internal static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porting Kit version.
        /// </summary>
        internal static string PK_VERSION_OPTION {
            get {
                return ResourceManager.GetString("PK_VERSION_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Specific.
        /// </summary>
        internal static string ProcessorSpecific {
            get {
                return ResourceManager.GetString("ProcessorSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPath.
        /// </summary>
        internal static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Library Category.
        /// </summary>
        internal static string SaveLibraryCategory {
            get {
                return ResourceManager.GetString("SaveLibraryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Features.
        /// </summary>
        internal static string SearchInFeatures {
            get {
                return ResourceManager.GetString("SearchInFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Libraries.
        /// </summary>
        internal static string SearchInLibraries {
            get {
                return ResourceManager.GetString("SearchInLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in LibraryCategories.
        /// </summary>
        internal static string SearchInLibraryCategories {
            get {
                return ResourceManager.GetString("SearchInLibraryCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectToViewDescr.
        /// </summary>
        internal static string SelectToViewDescr {
            get {
                return ResourceManager.GetString("SelectToViewDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionList.
        /// </summary>
        internal static string SolutionList {
            get {
                return ResourceManager.GetString("SolutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        internal static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionWizard.
        /// </summary>
        internal static string SolutionWizard {
            get {
                return ResourceManager.GetString("SolutionWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stub library.
        /// </summary>
        internal static string StubLibrary {
            get {
                return ResourceManager.GetString("StubLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Components searched.
        /// </summary>
        internal static string TotalComponentsSearched {
            get {
                return ResourceManager.GetString("TotalComponentsSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes in.
        /// </summary>
        internal static string Unsaved {
            get {
                return ResourceManager.GetString("Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is void.
        /// </summary>
        internal static string VoidDirectoryField {
            get {
                return ResourceManager.GetString("VoidDirectoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
