//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "LPC24XX_ADC.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_LPC24XX_ADC_NXP_Interop_ADC::Initialize___VOID__I2,
    Library_LPC24XX_ADC_NXP_Interop_ADC::Uninitialize___VOID,
    Library_LPC24XX_ADC_NXP_Interop_ADC::On___VOID,
    Library_LPC24XX_ADC_NXP_Interop_ADC::Off___VOID,
    Library_LPC24XX_ADC_NXP_Interop_ADC::GetSample___I4,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LPC24XX_ADC =
{
    "LPC24XX_ADC", 
    0xC2DD728B,
    method_lookup
};

