//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LPC24XX_ADC_H_
#define _LPC24XX_ADC_H_

#include <TinyCLR_Interop.h>
struct Library_LPC24XX_ADC_NXP_Interop_ADC
{
    TINYCLR_NATIVE_DECLARE(Initialize___VOID__I2);
    TINYCLR_NATIVE_DECLARE(Uninitialize___VOID);
    TINYCLR_NATIVE_DECLARE(On___VOID);
    TINYCLR_NATIVE_DECLARE(Off___VOID);
    TINYCLR_NATIVE_DECLARE(GetSample___I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LPC24XX_ADC;

#endif  //_LPC24XX_ADC_H_
