//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the build
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#define PLATFORM_NO_CLR_TRACE 1
#define TINYCLR_NO_IL_INLINE 1
