//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKStudio.Dialogs.ManageProjectWizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageProjectAndSolutionWizardsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageProjectAndSolutionWizardsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKStudio.Dialogs.ManageProjectWizard.ManageProjectAndSolutionWizardsStrings", typeof(ManageProjectAndSolutionWizardsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string IDS_BTN_TEXT_ALL {
            get {
                return ResourceManager.GetString("IDS_BTN_TEXT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved.
        /// </summary>
        internal static string IDS_BTN_TEXT_UNRESOLVED {
            get {
                return ResourceManager.GetString("IDS_BTN_TEXT_UNRESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IDS_ERROR {
            get {
                return ResourceManager.GetString("IDS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string IDS_FINISH_BTN_NAME {
            get {
                return ResourceManager.GetString("IDS_FINISH_BTN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string IDS_NEXT_BTN_NAME {
            get {
                return ResourceManager.GetString("IDS_NEXT_BTN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string IDS_NO {
            get {
                return ResourceManager.GetString("IDS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the features for the project.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_FEATURES {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the implementation to include for these libraries.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_LIBRARIES {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_LIBRARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the details of the new solution.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_NEW_SOLUTION_SUMMARY {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_NEW_SOLUTION_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the processor.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_PROCESSOR {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose processor settings for the solution.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_PROCESSOR_CFG {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_PROCESSOR_CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a name and description for the project.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_PROJECT_INFO {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_PROJECT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a name and description for the solution.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_SOLUTION_INFO {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_SOLUTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the projects to include in this solution.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_SOLUTION_PROJECTS {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_SOLUTION_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose project type.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_TEMPLATE {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the debugger port for the solution.
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_TRANSPORT {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_TRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Selection.
        /// </summary>
        internal static string IDS_PAGE_NAME_FEATURES {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Selection.
        /// </summary>
        internal static string IDS_PAGE_NAME_LIBRARIES {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_LIBRARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Summary.
        /// </summary>
        internal static string IDS_PAGE_NAME_NEW_SOLUTION_SUMMARY {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_NEW_SOLUTION_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string IDS_PAGE_NAME_PROCESSOR {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor settings.
        /// </summary>
        internal static string IDS_PAGE_NAME_PROCESSOR_CFG {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_PROCESSOR_CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project properties.
        /// </summary>
        internal static string IDS_PAGE_NAME_PROJECT_INFO {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_PROJECT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution properties.
        /// </summary>
        internal static string IDS_PAGE_NAME_SOLUTION_INFO {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_SOLUTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Selection.
        /// </summary>
        internal static string IDS_PAGE_NAME_SOLUTION_PROJECTS {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_SOLUTION_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project template selection.
        /// </summary>
        internal static string IDS_PAGE_NAME_TEMPLATE {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger port.
        /// </summary>
        internal static string IDS_PAGE_NAME_TRANSPORT {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_TRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IDS_YES {
            get {
                return ResourceManager.GetString("IDS_YES", resourceCulture);
            }
        }
    }
}
