//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKStudio.Tools.uVisionGenerator.Wizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeilWizardStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeilWizardStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PKStudio.Tools.uVisionGenerator.Wizard.KeilWizardStrings", typeof(KeilWizardStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist..
        /// </summary>
        internal static string IDS_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("IDS_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse links....
        /// </summary>
        internal static string IDS_ANALYSE_LINKS {
            get {
                return ResourceManager.GetString("IDS_ANALYSE_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse libraries links....
        /// </summary>
        internal static string IDS_ANALYSE_LYBRARIES_LINKS {
            get {
                return ResourceManager.GetString("IDS_ANALYSE_LYBRARIES_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse objects links....
        /// </summary>
        internal static string IDS_ANALYSE_OBJECTS_LINKS {
            get {
                return ResourceManager.GetString("IDS_ANALYSE_OBJECTS_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t build project.
        /// </summary>
        internal static string IDS_BUILD_ERROR {
            get {
                return ResourceManager.GetString("IDS_BUILD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building....
        /// </summary>
        internal static string IDS_BUILDING {
            get {
                return ResourceManager.GetString("IDS_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check links....
        /// </summary>
        internal static string IDS_CHECK_LINKS {
            get {
                return ResourceManager.GetString("IDS_CHECK_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert comleted.
        /// </summary>
        internal static string IDS_CONVERT_COLPETED {
            get {
                return ResourceManager.GetString("IDS_CONVERT_COLPETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert failed.
        /// </summary>
        internal static string IDS_CONVERT_FAILED {
            get {
                return ResourceManager.GetString("IDS_CONVERT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converted.
        /// </summary>
        internal static string IDS_CONVERTED {
            get {
                return ResourceManager.GetString("IDS_CONVERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting project.
        /// </summary>
        internal static string IDS_CONVERTING_PROJECT {
            get {
                return ResourceManager.GetString("IDS_CONVERTING_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert started.
        /// </summary>
        internal static string IDS_CONVERTING_STARTED {
            get {
                return ResourceManager.GetString("IDS_CONVERTING_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert completed.
        /// </summary>
        internal static string IDS_CONVERTION_COMPLITED {
            get {
                return ResourceManager.GetString("IDS_CONVERTION_COMPLITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating file list....
        /// </summary>
        internal static string IDS_CREATING_FILE_LIST {
            get {
                return ResourceManager.GetString("IDS_CREATING_FILE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project tree....
        /// </summary>
        internal static string IDS_CREATING_PROJECT_TREE {
            get {
                return ResourceManager.GetString("IDS_CREATING_PROJECT_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating targets....
        /// </summary>
        internal static string IDS_CREATING_TARGETS {
            get {
                return ResourceManager.GetString("IDS_CREATING_TARGETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description field is empty..
        /// </summary>
        internal static string IDS_DESCRIPTION_FIELD_EMPTY {
            get {
                return ResourceManager.GetString("IDS_DESCRIPTION_FIELD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string IDS_DONE {
            get {
                return ResourceManager.GetString("IDS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IDS_ERROR {
            get {
                return ResourceManager.GetString("IDS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find compile file options..
        /// </summary>
        internal static string IDS_ERROR_CANT_FIND_COMPILE_FILE_OPTIONS {
            get {
                return ResourceManager.GetString("IDS_ERROR_CANT_FIND_COMPILE_FILE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find library file options..
        /// </summary>
        internal static string IDS_ERROR_CANT_FIND_LIBRARY_FILE_OPTIONS {
            get {
                return ResourceManager.GetString("IDS_ERROR_CANT_FIND_LIBRARY_FILE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find property.
        /// </summary>
        internal static string IDS_ERROR_CANT_FIND_PROPERTY {
            get {
                return ResourceManager.GetString("IDS_ERROR_CANT_FIND_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link parsing error.
        /// </summary>
        internal static string IDS_ERROR_CANT_PASRSE_LINK {
            get {
                return ResourceManager.GetString("IDS_ERROR_CANT_PASRSE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read file..
        /// </summary>
        internal static string IDS_ERROR_CANT_READ_FILE {
            get {
                return ResourceManager.GetString("IDS_ERROR_CANT_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link analyse failed.
        /// </summary>
        internal static string IDS_ERROR_FAIL_LINK_ANALYSE {
            get {
                return ResourceManager.GetString("IDS_ERROR_FAIL_LINK_ANALYSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        internal static string IDS_ERROR_INTERNAL {
            get {
                return ResourceManager.GetString("IDS_ERROR_INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path..
        /// </summary>
        internal static string IDS_ERROR_INVALID_PATH {
            get {
                return ResourceManager.GetString("IDS_ERROR_INVALID_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select processor..
        /// </summary>
        internal static string IDS_ERROR_SELECT_PROCESSOR {
            get {
                return ResourceManager.GetString("IDS_ERROR_SELECT_PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more projects..
        /// </summary>
        internal static string IDS_ERROR_SELECT_PROJECT {
            get {
                return ResourceManager.GetString("IDS_ERROR_SELECT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file format..
        /// </summary>
        internal static string IDS_ERROR_WRONG_FILE_FORMAT {
            get {
                return ResourceManager.GetString("IDS_ERROR_WRONG_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string IDS_EXIT {
            get {
                return ResourceManager.GetString("IDS_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string IDS_FILE {
            get {
                return ResourceManager.GetString("IDS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string IDS_FILES {
            get {
                return ResourceManager.GetString("IDS_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing..
        /// </summary>
        internal static string IDS_MISSING {
            get {
                return ResourceManager.GetString("IDS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is empty..
        /// </summary>
        internal static string IDS_NAME_FIELD_EMPTY {
            get {
                return ResourceManager.GetString("IDS_NAME_FIELD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool is not supported.
        /// </summary>
        internal static string IDS_NOT_SUPPORTED_TOOL {
            get {
                return ResourceManager.GetString("IDS_NOT_SUPPORTED_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting project....
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_CONVERTING {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_CONVERTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro bla bla bla..
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_INTRO {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of convertation..
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_RESULTS {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory for solution..
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_SELECT_DIRECTORY {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_SELECT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select processor settings for uVision project..
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_SELECT_PROCESSOR {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_SELECT_PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Projects and their configuration to add in uVision solution..
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_SELECT_PROJECT {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_SELECT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary information about convertation..
        /// </summary>
        internal static string IDS_PAGE_DESCRIPTION_SUMMARY {
            get {
                return ResourceManager.GetString("IDS_PAGE_DESCRIPTION_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting.
        /// </summary>
        internal static string IDS_PAGE_NAME_CONVERTING {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_CONVERTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        internal static string IDS_PAGE_NAME_INTRO {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string IDS_PAGE_NAME_RESULTS {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory.
        /// </summary>
        internal static string IDS_PAGE_NAME_SELECT_DIRECTORY {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_SELECT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor settings.
        /// </summary>
        internal static string IDS_PAGE_NAME_SELECT_PROCESSOR {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_SELECT_PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select projects and configurations.
        /// </summary>
        internal static string IDS_PAGE_NAME_SELECT_PROJECT {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_SELECT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string IDS_PAGE_NAME_SUMMARY {
            get {
                return ResourceManager.GetString("IDS_PAGE_NAME_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string IDS_PROJECT {
            get {
                return ResourceManager.GetString("IDS_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory for solution..
        /// </summary>
        internal static string IDS_SELECT_DIRECTORY {
            get {
                return ResourceManager.GetString("IDS_SELECT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        internal static string IDS_TARGETS {
            get {
                return ResourceManager.GetString("IDS_TARGETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing files....
        /// </summary>
        internal static string IDS_WRITING_FILES {
            get {
                return ResourceManager.GetString("IDS_WRITING_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file format.
        /// </summary>
        internal static string IDS_WRONG_FILE_FORMAT {
            get {
                return ResourceManager.GetString("IDS_WRONG_FILE_FORMAT", resourceCulture);
            }
        }
    }
}
